app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('authentication.urls')),
    path("", include('customer.urls')),
    path("", include('hotel_manager.urls')),
    path("", include('room_booking.urls')),
    path("pay/", include('payment.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

room_booking/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('hotel/room/<int:pk>', views.create_booking, name='create_booking'),
    path('hotel/room/<int:book_pk>/checkout', views.booking_checkout, name='booking_checkout'),
    path('book/notify', views.booking_notify, name='booking_notify'),
    path('book/<int:book_pk>/checkin', views.guest_check_in, name='guest_check_in'),
    path('book/<int:book_pk>/hotel-cancel', views.hotel_guest_cancel, name='hotel_guest_cancel'),
    path('book/<int:book_pk>/seen-notify', views.redirect_notify, name='redirect_notify'),
]

room_booking/models.py
from datetime import datetime

from django.db import models

from authentication.models import User
from hotel_manager.models import HotelDetails
from payment.models import Payment


class DrinkAndFood(models.Model):
    MENU_TYPE = (
        (0, "Đồ ăn"),
        (1, "Nước uống"),
    )
    hotel_id = models.ForeignKey(HotelDetails, on_delete=models.CASCADE, related_name="hotel_menu")
    menu_type = models.IntegerField(choices=MENU_TYPE, default=0)
    item_name = models.CharField(max_length=255, unique=True)
    total = models.IntegerField(default=0)
    price = models.FloatField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.item_name


class RoomPriceDetails(models.Model):
    room_type = models.CharField(max_length=255)
    hotel = models.ForeignKey(
        HotelDetails, on_delete=models.CASCADE, related_name="rooms_hotel_prices", blank=True, null=True
    )
    price_per_day = models.PositiveIntegerField(default=0)
    price_first_two_hours = models.PositiveIntegerField(default=0)
    price_next_hours = models.PositiveIntegerField(default=0)
    price_per_night = models.PositiveIntegerField(default=0)
    max_person = models.PositiveIntegerField(default=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.room_type


class RoomDetails(models.Model):
    ROOM_STATUS = (('E', 'Trống'), ('C', 'Đang dọn'), ('L', 'Cho thuê'))
    room_name = models.CharField(max_length=255)
    room_no = models.PositiveIntegerField(null=True)
    hotel = models.ForeignKey(HotelDetails, on_delete=models.CASCADE, related_name='room_hotel')
    room_price = models.ForeignKey(RoomPriceDetails, on_delete=models.CASCADE, blank=True, null=True)
    layout = models.TextField(blank=True)
    introduce = models.TextField(blank=True)
    rating_star = models.FloatField(blank=True, null=True)
    size = models.CharField(max_length=255, blank=True, default="30")
    floor_no = models.PositiveIntegerField(default=0)
    room_status = models.CharField(choices=ROOM_STATUS, max_length=1, default="E")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.room_name


class BookingDetails(models.Model):
    BOOKING_STATUS = (
        ('KH', 'Khách hàng hủy'), ('KSH', 'Khách sạn hủy'), ('TP', 'Trả phòng'), ('DP', 'Đặt phòng'),
        ("NP", "Nhận phòng")
    )
    booking_id = models.AutoField(primary_key=True)
    guest = models.ForeignKey(
        User, to_field='username', on_delete=models.CASCADE, null=True, related_name="guest_bookings"
    )
    guest_name = models.CharField(max_length=255, blank=True, null=True)
    guest_phone_number = models.CharField(max_length=255, blank=True, null=True)
    BOOKING_TYPE = ((0, "Nghỉ giờ"), (1, "Nghỉ qua đêm"), (2, "Nghỉ ngày"))
    booking_type = models.IntegerField(choices=BOOKING_TYPE, default=0)
    hotel = models.ForeignKey(HotelDetails, on_delete=models.CASCADE, related_name="hotel_bookings")
    booking_status = models.CharField(max_length=3, choices=BOOKING_STATUS, default='DP')
    check_in_time = models.DateTimeField(null=True, blank=True)
    check_out_time = models.DateTimeField(null=True, blank=True)
    room = models.ForeignKey(RoomDetails, on_delete=models.CASCADE, related_name="room_bookings")
    total_guests = models.PositiveIntegerField(default=0)
    total_cost = models.FloatField(default=0)
    discounted_price = models.FloatField(default=0)
    booking_date = models.DateTimeField(auto_now_add=True)
    seen = models.BooleanField(default=False)
    pre_order = models.BooleanField(default=False)
    is_pay = models.BooleanField(default=False)
    pay_online = models.OneToOneField(
        Payment, on_delete=models.DO_NOTHING, related_name="pay_online", null=True, blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.guest_name


class DrinkAndFoodOrder(models.Model):
    drink_and_food = models.ForeignKey(DrinkAndFood, related_name="food", on_delete=models.DO_NOTHING)
    book = models.ForeignKey(BookingDetails, related_name="menu", on_delete=models.DO_NOTHING, default=None)
    total = models.IntegerField(default=0)
    amount = models.FloatField(default=0)
    accept = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return str(self.drink_and_food)


class Photos(models.Model):
    hotel_id = models.ForeignKey(
        HotelDetails, on_delete=models.CASCADE, related_name='hotel_photos', blank=True, null=True
    )
    room_id = models.ForeignKey(
        RoomDetails, on_delete=models.CASCADE, blank=True, null=True, related_name='room_photos'
    )
    FOLDER_NAME = datetime.strftime(datetime.now(), "%Y%m%d")
    image_hotel = models.ImageField(upload_to=f'hotels/{FOLDER_NAME}/', blank=True, null=True)
    image_room = models.ImageField(upload_to=f'rooms/{FOLDER_NAME}/', blank=True, null=True)
    image_name = models.CharField(max_length=255, default="image")
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.image_name

room_booking/views.py
import json
import math
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q, Sum
from django.http import HttpResponse
from django.shortcuts import redirect, render

from hotel_manager.models import HotelDetails
from room_booking.models import BookingDetails, DrinkAndFoodOrder, RoomDetails
from websocket.redis_publish import publish_event

from .forms import BookingCheckOutForms, BookingDetailsForms

# Create your views here.


@login_required(login_url='/signin')
def create_booking(request, pk):
    room_book = RoomDetails.objects.get(pk=pk)
    if request.method == 'POST':
        request.POST = request.POST.copy()
        request.POST['room'] = room_book.pk
        request.POST['pre_order'] = True
        form = BookingDetailsForms(request.POST or None)

        if form.is_valid():
            booking = form.save(commit=False)
            booking.guest = request.user
            booking.hotel = room_book.hotel
            booking.room = room_book

            booking.save()

            hotel_owner = room_book.hotel.owner.pk
            event = {"event_type": "reload_notify", "payload": {"user_id": hotel_owner}}
            channel = f"notify_{hotel_owner}"
            publish_event(channel=channel, event=event)
            if request.user == room_book.hotel.owner:
                messages.success(request, "Đặt phòng thành công")
                return redirect('home')
            else:
                book_pre = BookingDetails.objects.get(booking_id=booking.booking_id)
                book_pre.pre_order = True
                book_pre.save()
                request.session['payment_status'] = 'booking'
                messages.success(request, "Đặt phòng thành công")
                return redirect("payment", book_pk=book_pre.booking_id)
    else:
        form = BookingDetailsForms()

    context = {"form": form, "room_book": room_book}
    return render(request, 'bookings/booking_create.html', context)


@login_required(login_url='/signin')
def staff_create_booking(request, pk):
    room_book = RoomDetails.objects.get(pk=pk)
    if request.method == 'POST':
        form = BookingDetailsForms(request.POST or None)

        if form.is_valid():
            booking = form.save(commit=False)
            booking.hotel = room_book.hotel
            booking.room = room_book

            booking.save()
            messages.success(request, "Đặt phòng thành công")
            return redirect('home')
    else:
        form = BookingDetailsForms()

    context = {"form": form, "room_book": room_book}
    return render(request, 'bookings/booking_create.html', context)


@login_required(login_url='/signin')
def booking_checkout(request, book_pk):
    try:
        book = BookingDetails.objects.get(pk=book_pk)
        more_money = 0
        if book.booking_type == 0:
            more_hours = math.ceil((book.check_out_time - book.check_in_time).total_seconds() / 3600) - 2
            book.total_cost = book.room.room_price.price_first_two_hours + (
                more_hours * book.room.room_price.price_next_hours
            )
        if book.booking_type == 1:
            more_hours = math.ceil((book.check_out_time - book.check_in_time).total_seconds() / 3600)
            if more_hours > 12:
                more_money = book.room.room_price.price_next_hours * (more_hours - 12)
            book.total_cost = book.room.room_price.price_per_night + more_money
        if book.booking_type == 2:
            more_hours = math.ceil((book.check_out_time - book.check_in_time).total_seconds() / 3600)
            day = math.ceil(more_hours / 24)
            book.total_cost = day * book.room.room_price.price_per_day

        try:
            menu = DrinkAndFoodOrder.objects.filter(book=book).aggregate(Sum('amount'))
            book.total_cost = book.total_cost + menu['amount__sum']
        except TypeError:
            pass
        book.booking_status = "TP"
    except BookingDetails.DoesNotExist:
        return redirect(request.META.get('HTTP_REFERER'))

    book_form = BookingCheckOutForms(request.POST or None, instance=book)
    if request.method == 'POST':
        if book_form.is_valid():
            room = RoomDetails.objects.get(pk=book.room.pk)
            room.room_status = "E"
            room.save()
            book_form.save()
            if book_form.cleaned_data['refund'] in {None, "False", False}:
                book = BookingDetails.objects.filter(booking_id=book_pk).first()
                book.is_pay = True
                book.save()
                messages.success(request, "Trả phòng thành công")
                return redirect("home")
            request.session["refund_status"] = "hotel"
            request.session["booking_pk"] = book_pk
            return redirect("payment_refund", book_pk=book_pk)

    pay_online = None
    if book.pay_online is not None:
        pay_online = book.pay_online.amount

    room_name = book.room.room_name

    context = {
        "form": book_form,
        "pay_online": pay_online,
        "menu": menu['amount__sum'],
        "room_name": room_name,
        "book_pk": book_pk,
        "total_cost": book.total_cost or 0,
        "screen": "checkout"
    }

    return render(request, 'bookings/booking_checkout.html', context)


@login_required(login_url='/signin')
def guest_check_in(request, book_pk):
    if request.method == 'POST':
        try:
            book = BookingDetails.objects.get(pk=book_pk)
            if book.pre_order:
                if book.pay_online is not None:
                    if book.pay_online.amount < 200000:
                        messages.warning(request, "Khách chưa đặt cọc đủ tiền phòng")
                        return redirect("my_hotel_book", hotel_pk=book.hotel.pk)
                    else:
                        book.booking_status = "NP"
                        book.room.room_status = "L"
                        book.room.save()
                        book.seen = True
                        book.save()
                        return redirect('my_hotel_book', hotel_pk=book.hotel.pk)
                else:
                    messages.warning(request, "Khách chưa đặt cọc đủ tiền phòng")
                    return redirect("my_hotel_book", hotel_pk=book.hotel.pk)
            book.booking_status = "NP"
            book.room.room_status = "L"
            book.room.save()
            book.seen = True
            book.save()
        except BookingDetails.DoesNotExist:
            pass
        return redirect('my_hotel_book', hotel_pk=book.hotel.pk)


@login_required(login_url='/signin')
def hotel_guest_cancel(request, book_pk):
    if request.method == 'POST':
        try:
            book = BookingDetails.objects.get(pk=book_pk)
            if datetime.now() < book.check_in_time:
                if book.pay_online:
                    request.session["book_out"] = "True"
                    request.session["book_pk"] = book_pk
                    return redirect('payment_refund', book_pk=book_pk)
                book.booking_status = "KSH"
                book.room.room_status = "E"
                book.room.save()
                book.seen = True
                book.save()
                hotel_owner = book.hotel.owner.pk
                event = {"event_type": "reload_notify", "payload": {"user_id": hotel_owner}}
                channel = f"notify_{hotel_owner}"
                publish_event(channel=channel, event=event)
            else:
                if book.pay_online:
                    request.session["book_out"] = "True"
                    request.session["book_pk"] = book_pk
                    return redirect('payment_refund', book_pk=book_pk)
                else:
                    book.booking_status = "KSH"
                    book.room.room_status = "E"
                    book.room.save()
                    book.seen = True
                    book.save()
                    hotel_owner = book.hotel.owner.pk
                    event = {"event_type": "reload_notify", "payload": {"user_id": hotel_owner}}
                    channel = f"notify_{hotel_owner}"
                    publish_event(channel=channel, event=event)
        except BookingDetails.DoesNotExist:
            pass

        return redirect('my_hotel_book', hotel_pk=book.hotel.pk)


def booking_notify(request):
    user_pk = request.GET.get("user_pk")
    hotels = HotelDetails.objects.filter(owner__pk=user_pk).values('pk')
    books_all = BookingDetails.objects.filter(Q(hotel__pk__in=hotels) & Q(booking_status='DP') & Q(seen=False))
    count = books_all.count()
    books = books_all.values("booking_id", "hotel__name", "guest_name", "hotel__hotel_photos__image_hotel")

    hotels_np = HotelDetails.objects.filter(owner__pk=user_pk)
    books_np = BookingDetails.objects.filter(Q(hotel__in=hotels_np) & Q(booking_status="NP")).all()
    menus = []

    for book in books_np:
        menu = book.menu.filter(
            accept=False
        ).values("book__hotel__pk", "book__hotel__name", "book__hotel__hotel_photos__image_hotel", "book__guest_name")
        if menu:
            menus.extend(menu)

    menus_count = len(menus)

    return HttpResponse(
        json.dumps({
            "count": count,
            "books": list(books),
            "menus_count": menus_count,
            "menus": menus,
        })
    )


@login_required(login_url='/signin')
def redirect_notify(request, book_pk):
    if request.method == 'POST':
        try:
            book = BookingDetails.objects.get(pk=book_pk)
        except BookingDetails.DoesNotExist:
            pass
    return redirect('my_hotel_book', hotel_pk=book.hotel.pk)

room_booking/templates/bookings/booking_checkout.html
{% extends "base.html" %}
{% load static %}
{% load template_support %}
{% load crispy_forms_tags %}
{% block title %}
    Trả phòng
{% endblock title %}
{% block body %}
    <section class="bg-image create-hotel-section pt-4 pb-4"
             style="background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.webp');">
        <div class="gradient-custom-4">
            <div class="container-fluid">
                <div class="row justify-content-center align-items-center h-100">
                    <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                        <div class="card" style="border-radius: 15px;">
                            <div class="card-body p-5">
                                <h2 class="text-uppercase text-center mb-5">Trả phòng: {{ room_name }}</h2>
                                <form action="" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {% for field in form %}
                                        {% if field.name == 'refund' %}
                                            {% if pay_online != None %}
                                                {% include 'field.html' %}
                                            {% endif %}
                                        {% else %}
                                            {% include 'field.html' %}
                                        {% endif %}
                                    {% endfor %}
                                    {% if pay_online != None %}
                                        <div class="form-group mb-4">Tiền đã đặt {{ pay_online }} VNĐ</div>
                                        {% endif %}
                                    {% if menu %}
                                        <div class="form-group mb-4">Tiền đồ ăn/nước uống là {{ menu }} VNĐ</div>
                                    {% endif %}
                                    <div class="form-group mb-4">{{ file_form }}</div>
                                    <div class="pt-2 pb-2 pr-5 justify-content-end align-items-end d-flex">
                                        <button class="btn btn-outline-primary btn-lg" type="submit">Trả phòng</button>
                                    </div>
                                </form>
                                <img id="qr_code_id" src="{% url 'generate_qrcode' book_pk=book_pk %}?money={{total_cost}}" alt="QR Code" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock body %}
{% block footer %}
    <style type="text/css">
        .nice-select {
            width: 100%;
        }
    </style>
    <script>

    </script>
{% endblock footer %}

{% block script %}
    <script type="text/javascript">
        $(document).ready(function () {
            $("#id_total_cost").on("keyup", function() {
                total_cost = $(this).val()
                $("#qr_code_id").attr("src", `{% url 'generate_qrcode' book_pk=book_pk %}?money=${total_cost}`)
            })
        })
    </script>
{% endblock script %}

room_booking/templates/bookings/booking_create.html
{% extends "base.html" %}
{% load static %}
{% load template_support %}
{% load crispy_forms_tags %}
{% block title %}
    Phòng ở
{% endblock title %}
{% block body %}
    <!-- Room Details Section Begin -->
    <section class="room-details-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="room-details-item">
                        <img src="{{ room_book.room_photos.first.image_room.url }}" alt="" />
                        <div class="rd-text">
                            <div class="rd-title">
                                <h3>{{ room_book.room_name }}</h3>
                            </div>
                            <h2>{{ room_book.room_price.price_per_night|currency }}VNĐ<span>/Một đêm</span></h2>
                            <table>
                                <tbody>
                                    <tr>
                                        <td class="r-o">Diện tích:</td>
                                        <td>{{ room_book.size }}m2</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Số người tối đa:</td>
                                        <td>{{ room_book.room_price.max_person }}</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Dịch vụ:</td>
                                        <td>{{ room_book.layout }}</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Trạng thái phòng:</td>
                                        <td>{{ room_book.room_status|get_full_room_status }}</td>
                                    </tr>
                                </tbody>
                            </table>
                            <p class="f-para">{{ room_book.introduce }}</p>
                        </div>
                    </div>
                    <div class="rd-reviews row">
                        <h4>Nhận xét</h4>
                        <div id="reviews-comment" class="col-12">
                            {% comment %}  comment {% endcomment %}
                        </div>
                        <div class="col-lg-12">
                        <div id="room-pagination" class="room-pagination">
                            {% comment %} pagination {% endcomment %}
                        </div>
                    </div>
                    </div>
                    <div class="review-add">
                        <h4>Thêm nhận xét</h4>
                        <div class="ra-form">
                            <div class="row">
                                <div class="col-lg-6">
                                    <label>Tên đăng nhập</label>
                                    <input type="text" class="text-dark" placeholder="Name*" value="{{ request.user.username }}" />
                                </div>
                                <div class="col-lg-6">
                                    <label>Email</label>
                                    <input type="text" class="text-dark" placeholder="Email*" value="{{ request.user.email }}" />
                                </div>
                                <div class="col-lg-12">
                                    <div>
                                        <h5>Đánh giá của bạn:</h5>
                                        <div id="rating-star" class="rating">
                                        </div>
                                    </div>
                                    <textarea id="comment-content" placeholder="Nhận xét của bạn"></textarea>
                                    <button onclick="Comment()">Nhận xét</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="room-booking">
                        <h3>Đặt phòng của bạn</h3>
                        <form action="#" method="post">
                            {% csrf_token %}
                            {% for field in form %}
                                {% include 'field.html' %}
                            {% endfor %}
                            <button type="submit">Đặt phòng</button>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </section>
    <!-- Room Details Section End -->
{% endblock body %}
{% block footer %}
    <style type="text/css">
        .nice-select {
            width: 100%;
        }
    </style>
{% endblock footer %}

{% block script %}
    <script type="text/javascript">
        var csrftoken = $("[name=csrfmiddlewaretoken]").val();
        var thisPage = null;
        var perPage = null;

        function loadCommnets(page=1) {
            $.ajax({
                url: "{% url 'load_comments' %}",
                type: "GET",
                headers: {
                    "X-CSRFToken": csrftoken
                },
                data: {
                    room_pk: {{ room_book.pk }},
                    page: page
                },
                dataType: 'json',
                success: function(response) {
                    thisPage = response.this_page
                    perPage = response.per_page
                    if (response.comment != []) {
                        $("#reviews-comment").empty();
                        response.comment.forEach(cmt => {
                            html = `<div class="review-item">
                                    <div class="ri-pic">
                                        <img src="{{ room_book.room_photos.first.image_room.url }}" alt="" />
                                    </div>
                                    <div class="ri-text">
                                        <span>${cmt.created_at__day}/${cmt.created_at__month}/${cmt.created_at__year}</span>
                                        <div class="rating">
                                        </div>
                                        <h5>${cmt.user__username}</h5>
                                        <p>${cmt.comment}</p>
                                    </div>
                                </div>`
                            $("#reviews-comment").append(html)
                        })

                        if (response.pages > 1) {
                            $("#room-pagination").empty()
                            if (response.previous) {
                                $("#room-pagination").append(`<a class="btn" onclick="changePage('${response.previous}')"><i class="fa fa-long-arrow-left"></i></a>`)
                            }
                            for (let i = 1; i <= response.pages; i++) {
                                $("#room-pagination").append(`<a class="btn" onclick="changePage('${i}')">${i}</a>`)
                            }
                            if (response.next) {
                                $("#room-pagination").append(`<a class="btn" onclick="changePage('${response.next}')"><i class="fa fa-long-arrow-right"></i></a>`)
                            }
                        }
                    }
                },
                error: function(request, status, error) {
                    alert(request.responseText);
                }
            });
        }

        function changePage (page) {
            page = parseInt(page)
            if (thisPage != page) {
                loadCommnets(page)
            }
        }

        function Comment() {
            var comment = $("#comment-content").val()
            if (comment.trim() != "" && comment != null && comment != undefined){
                console.log(comment)
                $.ajax({
                    url: "{% url 'create_comment' %}",
                    type: "POST",
                    headers: {
                        "X-CSRFToken": csrftoken
                    },
                    data: {
                        room_pk: {{ room_book.pk }},
                        comment: comment
                    },
                    dataType: 'json',
                    success: function(response) {
                        if (response.comment) {
                            $("#comment-content").val('')
                            html = `<div class="review-item">
                                        <div class="ri-pic">
                                            <img src="{{ room_book.room_photos.first.image_room.url }}" alt="" />
                                        </div>
                                        <div class="ri-text">
                                            <span>${response.c_date}</span>
                                            <div class="rating">
                                            </div>
                                            <h5>${response.user}</h5>
                                            <p>${response.comment}</p>
                                        </div>
                                    </div>`
                            if ($(".review-item").length >= perPage) {
                                loadCommnets();
                            } else {
                                $("#reviews-comment").prepend(html);
                            }
                        }
                    },
                    error: function(request, status, error) {
                        alert(request.responseText);
                    }
                });
            }
        }

        $(document).ready(function () {
            $("#rating-star").rateYo({
                starWidth: "40px",
                halfStar: true,
                onSet: function (rating, rateYoInstance) {
                    $.ajax({
                        url: "{% url 'create_rating' %}",
                        type: "POST",
                        headers: {
                            "X-CSRFToken": csrftoken
                        },
                        data: {
                            room_pk: {{ room_book.pk }},
                            rating: rating
                        },
                        dataType: 'json',
                        success: function(response) {
                            if (response.rating) {
                            }
                        },
                        error: function(request, status, error) {
                            alert(request.responseText);
                        }
                });
                },
            });
            // set
            //var rating = $("#rating-star").rateYo("option", "rating")
            // get
            var ratingStar = "{{ room_book.rating_star }}"
            if (ratingStar != "None") {
                $("#rating-star").rateYo("option", "rating", parseFloat(ratingStar))
            }
        })
        window.onload = function() {
            loadCommnets();
        }
    </script>
{% endblock script %}