app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('authentication.urls')),
    path("", include('customer.urls')),
    path("", include('hotel_manager.urls')),
    path("", include('room_booking.urls')),
    path("pay/", include('payment.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel_manager/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('hotel/create/', views.create_hotel, name='hotel_create'),
    path('hotel/my', views.my_hotels, name='my_hotel'),
    path('hotel/<int:pk>/rooms/', views.hotel_rooms, name='hotel_rooms'),
    path('hotel/<int:pk>/my_rooms/', views.my_hotel_rooms, name='my_hotel_rooms'),
    path('hotel/<int:hotel_pk>/new-room/', views.create_room_hotel, name='hotel_new_room'),
    path('hotel/<int:hotel_pk>/room-price/', views.create_room_price, name='hotel_room_price'),
    path('hotel/<int:hotel_pk>/books/', views.my_hotel_book, name='my_hotel_book'),
    path('hotel/<int:hotel_pk>/update-hotel/', views.update_hotel_info, name='update_hotel_info'),
    path('hotel/<int:room_pk>/update-room/', views.update_room_hotel, name='update_room_hotel'),
    path('hotel/<int:room_pk>/empty-room/', views.set_room_empty, name='set_room_empty'),
    path('hotel/<int:hotel_pk>/dashboard/', views.dashboard, name='dashboard'),
    path('hotel/<int:hotel_pk>/room-prices/', views.list_room_price, name='list_room_price'),
    path('hotel/<int:room_price_pk>/room-price-update/', views.update_room_price, name='update_room_price'),
    path('hotel/<int:hotel_pk>/menus/', views.menu_food_drink, name='menu_food_drink'),
    path('hotel/<int:hotel_pk>/menu-create/', views.create_menu, name='create_menu'),
    path('hotel/<int:menu_pk>/menu-update/', views.update_menu, name='update_menu'),
    path('hotel/<int:hotel_pk>/list-order/', views.list_menu_order, name='list_menu_order'),
    path('hotel/<int:menu_pk>/accept-update/', views.accept_menu, name='accept_menu'),
    path('qrcode/<int:book_pk>/', views.generate_qrcode, name='generate_qrcode'),
]

hotel_manager/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

from authentication.models import User


class HotelDetails(models.Model):
    name = models.CharField(max_length=255, blank=True)
    email = models.EmailField(max_length=255, blank=True, unique=True)
    contact_no = PhoneNumberField(max_length=255, blank=True, region="VN")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="hotels")
    address = models.CharField(max_length=400, blank=True, unique=True)
    city = models.CharField(max_length=255, blank=True)
    introduce = models.TextField(blank=True)
    rating_star = models.FloatField(blank=True, null=True)
    latitude = models.CharField(blank=True, max_length=255)
    logtitude = models.CharField(blank=True, max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

hotel_manager/views.py
from datetime import datetime

import qrcode
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.sites.shortcuts import get_current_site
from django.db.models import Count, Q, Sum
from django.db.models.functions import TruncDay, TruncMonth, TruncYear
from django.http import HttpResponse
from django.shortcuts import redirect, render

from common.vietnam_province import VIETNAM_CITY
from middleware.paginator import paginator_list_function
from room_booking.forms import (
    PhotoForms,
    RoomDetailsForms,
    RoomPriceDetailsForms,
    SearchRoomsEmty,
    UpdatePhotoRoom,
)
from room_booking.models import (
    BookingDetails,
    DrinkAndFood,
    DrinkAndFoodOrder,
    Photos,
    RoomDetails,
    RoomPriceDetails,
)

from .forms import CreateUpdateMenu, HotelCreateForm, UpdatePhotoHotel
from .models import HotelDetails

hotel_search = None
data_search_global = None


# Create your views here.
def home(request):
    hotels = HotelDetails.objects.all().order_by("-id")
    global hotel_search
    global data_search_global

    if not request.GET.get("page"):
        data_search_global = None
        hotel_search = None

    if request.method == "POST":
        form = SearchRoomsEmty(request.POST)
        if form.is_valid():
            data_search = form.cleaned_data
            time_start = data_search.get('datetime_check_in')
            time_end = data_search.get('datetime_check_out')
            max_person = data_search.get('max_person')
            city = data_search.get('city')

            books_room = BookingDetails.objects.filter(
                (~Q(booking_status__contains='DP') | ~Q(booking_status__contains="NP"))
                & (Q(check_in_time__range=[time_start, time_end])
                   | Q(check_out_time__range=[time_start, time_end]))
            ).values('room__id')
            id_book_rooms = [room["room__id"] for room in books_room]
            all_rooms = RoomDetails.objects.filter(room_price__max_person__gte=max_person).exclude(id__in=id_book_rooms)
            hotel_ids = all_rooms.values('hotel__id').annotate(room_count=Count('hotel__id')).filter(room_count__gte=1)
            hotels = HotelDetails.objects.filter(
                Q(pk__in=[item['hotel__id'] for item in hotel_ids]) & Q(city__icontains=city)
            )
            hotel_search = hotels
            data_search_global = request.POST
            print(hotel_ids)
            pass
    else:
        if hotel_search is not None:
            hotels = hotel_search
        form = SearchRoomsEmty(data_search_global or None)

    hotels = paginator_list_function(hotels, request.GET.get("page"))
    context = {"menu": "home", "hotels": hotels, 'search_form': form, "vietnam_city": VIETNAM_CITY, "pages": hotels}
    return render(request, "hotels/index.html", context)


@login_required(login_url='/signin')
@user_passes_test(lambda user: user.is_staff or user.is_superuser)
def create_hotel(request):
    if request.method == "POST":
        hotel_create_form = HotelCreateForm(request.POST or None)
        photo_hotel_form = PhotoForms(request.POST, request.FILES)

        if hotel_create_form.is_valid() and photo_hotel_form.is_valid():
            new_hotel = hotel_create_form.save(commit=False)
            new_hotel.owner = request.user
            new_hotel.save()
            images = request.FILES.getlist('images')
            for image in images:
                photo = Photos.objects.create(hotel_id=new_hotel, image_hotel=image, image_name=image.name)
                photo.save()
                pass
            messages.success(request, "Tạo khách sạn thành công")
            return redirect('home')
    else:
        hotel_create_form = HotelCreateForm()
        photo_hotel_form = PhotoForms()

    context = {"form": hotel_create_form, "menu": "hotel", "file_form": photo_hotel_form, "vietnam_city": VIETNAM_CITY}

    return render(request, 'hotels/create_hotel.html', context)


@login_required(login_url='/signin')
@user_passes_test(lambda user: user.is_staff or user.is_superuser)
def my_hotels(request):
    hotels = request.user.hotels.all()

    context = {'hotels': hotels, "menu": "hotel"}
    return render(request, 'hotels/my_hotels.html', context)


@login_required(login_url='/signin')
def hotel_rooms(request, pk):
    room_prices = RoomPriceDetails.objects.filter(hotel__id=pk)

    rooms = RoomDetails.objects.filter(hotel__pk=pk)

    context = {"room_prices": room_prices, "rooms": rooms}
    return render(request, 'rooms/rooms_hotel.html', context)


@login_required(login_url='/signin')
def my_hotel_rooms(request, pk):
    room_prices = RoomPriceDetails.objects.filter(hotel__id=pk)

    rooms = RoomDetails.objects.filter(hotel__pk=pk)

    context = {"room_prices": room_prices, "rooms": rooms, "menu": "hotel"}
    return render(request, 'rooms/my_rooms_hotel.html', context)


@login_required(login_url='/signin')
def create_room_price(request, hotel_pk):
    hotel = HotelDetails.objects.get(pk=hotel_pk)

    if request.method == 'POST':
        form = RoomPriceDetailsForms(request.POST or None)
        if form.is_valid():
            room_price = form.save(commit=False)
            room_price.hotel = hotel
            room_price.save()

            return redirect('list_room_price', hotel_pk=hotel_pk)
    else:
        form = RoomPriceDetailsForms()

    context = {"form": form, "screen": 'hotel', "menu": "hotel"}

    return render(request, 'rooms/create_room_price.html', context)


@login_required(login_url='/signin')
def list_room_price(request, hotel_pk):
    try:
        room_prices = RoomPriceDetails.objects.filter(hotel__pk=hotel_pk)
    except RoomPriceDetails.DoesNotExist:
        room_prices = []
    context = {"room_prices": room_prices, "hotel_pk": hotel_pk}

    return render(request, 'rooms/list_room_price.html', context)


@login_required(login_url='/signin')
def update_room_price(request, room_price_pk):
    room_price = RoomPriceDetails.objects.get(pk=room_price_pk)

    form = RoomPriceDetailsForms(request.POST or None, instance=room_price)
    if request.method == "POST":
        if form.is_valid():
            form.save()

            return redirect('list_room_price', hotel_pk=room_price.hotel.pk)

    context = {"form": form, "room_price_name": room_price.room_type}
    return render(request, "rooms/update_room_price.html", context)


@login_required(login_url='/signin')
def create_room_hotel(request, hotel_pk):
    room_prices = RoomPriceDetails.objects.filter(hotel__pk=hotel_pk)

    if request.method == 'POST':
        form = RoomDetailsForms(request.POST or None)
        photo = PhotoForms(request.POST, request.FILES)

        if form.is_valid() and photo.is_valid():
            new_room = form.save(commit=False)
            hotel = HotelDetails.objects.get(pk=hotel_pk)
            new_room.hotel = hotel
            new_room.save()

            images = request.FILES.getlist('images')
            for image in images:
                photo = Photos.objects.create(room_id=new_room, image_room=image, image_name=image.name)
                photo.save()

            return redirect('hotel_rooms', pk=hotel_pk)
    else:
        form = RoomDetailsForms()
        photo = PhotoForms()
    context = {
        "form": form,
        "photo_form": photo,
        "room_prices": room_prices,
        "hotel_pk": hotel_pk,
        "screen": 'hotel',
        "menu": "hotel"
    }

    return render(request, 'rooms/create_room.html', context)


@login_required(login_url='/signin')
def update_room_hotel(request, room_pk):
    try:
        room = RoomDetails.objects.get(pk=room_pk)
        room_prices = RoomPriceDetails.objects.filter(hotel__pk=room.hotel.pk)
        photo = Photos.objects.filter(room_id=room_pk).first()
    except (RoomDetails.DoesNotExist, RoomPriceDetails.DoesNotExist, Photos.DoesNotExist):
        pass

    form = RoomDetailsForms(request.POST or None, instance=room)
    photo_form = UpdatePhotoRoom(request.POST, request.FILES, instance=photo)
    if photo_form.is_valid():
        photo_form.save()

    if form.is_valid():
        form.save()
        return redirect('my_hotel_rooms', pk=room.hotel.pk)

    context = {"form": form, 'screen': 'room', "room_prices": room_prices, "photo_form": photo_form, "room": room}

    return render(request, 'rooms/update_room.html', context)


@login_required(login_url='/signin')
def update_hotel_info(request, hotel_pk):
    try:
        hotel = HotelDetails.objects.get(pk=hotel_pk)
        photo = Photos.objects.filter(hotel_id=hotel_pk).first()
    except HotelDetails.DoesNotExist:
        pass

    form = HotelCreateForm(request.POST or None, instance=hotel)
    photo_form = UpdatePhotoHotel(request.POST, request.FILES, instance=photo)
    if photo_form.is_valid():
        photo_form.save()

    if form.is_valid():
        form.save()
        return redirect("my_hotel")
    context = {'form': form, "photo_form": photo_form, "menu": "hotel"}
    return render(request, "hotels/update_hotel.html", context)


@login_required(login_url='/signin')
def my_hotel_book(request, hotel_pk):
    hotel_books = BookingDetails.objects.filter(Q(hotel=hotel_pk) & (Q(booking_status="DP") | Q(booking_status="NP")))
    context = {"books": hotel_books, "menu": "hotel"}
    return render(request, 'hotels/my_hotel_books.html', context)


@login_required(login_url='/signin')
def set_room_empty(request, room_pk):
    try:
        room = RoomDetails.objects.get(pk=room_pk)
        room.room_status = "E"
        room.save()
    except RoomDetails.DoesNotExist:
        pass

    return redirect(request.path)


@login_required(login_url='/signin')
def dashboard(request, hotel_pk):
    books = BookingDetails.objects.filter(hotel__pk=hotel_pk, booking_status="TP")
    books_day = books.annotate(day=TruncDay('check_in_time')).values('day').annotate(

hotel_manager/templates/hotels/create_hotel.html
{% extends "base.html" %}
{% load static %}
{% load template_support %}
{% load crispy_forms_tags %}
{% block title %}
    Thêm khách sạn
{% endblock title %}
{% block body %}
    <section class="bg-image create-hotel-section pt-4 pb-4"
             style="background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.webp');">
        <div class="gradient-custom-4">
            <div class="container-fluid">
                <div class="row justify-content-center align-items-center h-100">
                    <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                        <div class="card" style="border-radius: 15px;">
                            <div class="card-body p-5">
                                <h2 class="text-uppercase text-center mb-5">Đăng ký khách sạn mới</h2>
                                <form action="" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {% for field in form %}
                                        {% include 'field.html' %}
                                    {% endfor %}
                                    <div class="form-group mb-4">{{ file_form }}</div>
                                    <div class="pt-2 pb-2 pr-5 justify-content-end align-items-end d-flex">
                                        <button class="btn btn-outline-primary btn-lg" type="submit">Thêm khách sạn</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock body %}
{% block script %}
    <style type="text/css"></style>
    <script type="text/javascript">
        var countries = {{ vietnam_city|safe }}
        $("#id_city").autocomplete({
            source: countries
        });
    </script>
{% endblock script %}

hotel_manager/templates/hotels/dashboard.html
{% extends "base.html" %}
{% load static %}
{% load template_support %}
{% load crispy_forms_tags %}
{% block title %}
    Phòng khách sạn
{% endblock title %}
{% block header %}
    <link rel="stylesheet"
          type="text/css"
          href="{% static 'css/adminlte.min.css' %}"/>
    <link rel="stylesheet"
          type="text/css"
          href="{% static 'css/jquery.dataTables.min.css' %}"/>
{% endblock header %}
{% block body %}
    <section class="content">
        <div class="container">
            <!-- Small boxes (Stat box) -->
            <div class="row">
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>{{ total_rooms|check_number_none }}</h3>
                            <p>Phòng</p>
                        </div>
                        <div class="icon">
                            <i class="fa fa-bed" aria-hidden="true"></i>
                        </div>
                        {% comment %} <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a> {% endcomment %}
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-success">
                        <div class="inner">
                            <h3>{{ total_cost__sum|check_number_none|currency }} VNĐ</h3>
                            <p>Tổng doanh thu</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-stats-bars"></i>
                        </div>
                        {% comment %} <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a> {% endcomment %}
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-warning">
                        <div class="inner text-white">
                            <h3>{{ pk__count|check_number_none }}</h3>
                            <p>Tổng khách thuê</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-add"></i>
                        </div>
                        {% comment %} <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a> {% endcomment %}
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-danger">
                        <div class="inner">
                            <h3>{{ cost_day|check_number_none|currency }} VNĐ</h3>
                            <p>Doanh thu hôm nay</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-pie-graph"></i>
                        </div>
                        {% comment %} <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a> {% endcomment %}
                    </div>
                </div>
                <!-- ./col -->
            </div>
            <div class="row ml-5">
                <div class="col-12 mt-5">
                    <h2>Doanh thu ngày</h2>
                    <div class="card-body table-responsive p-0">
                        <table id="invoice_day_table"
                               class="table table-striped table-valign-middle cell-border table-bordered text-center">
                            <thead>
                                <tr>
                                    <th>Ngày</th>
                                    <th>Số phòng thuê</th>
                                    <th>Tiền menu</th>
                                    <th>Doanh thu</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for book in books_day %}
                                    <tr>
                                        <td>{{ book.day|date:"d/m/Y" }}</td>
                                        <td>{{ book.total_book }}</td>
                                        <td>{{ book.menu_cost|currency }}</td>
                                        <td>{{ book.total_cost|currency }} VNĐ</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-12 mt-5">
                    <h2>Doanh thu tháng</h2>
                    <div class="card-body table-responsive p-0">
                        <table id="invoice_month_table"
                               class="table table-striped table-valign-middle cell-border table-bordered text-center">
                            <thead>
                                <tr>
                                    <th>Tháng</th>
                                    <th>Số phòng thuê</th>
                                    <th>Tiền menu</th>
                                    <th>Doanh thu</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for book in books_month %}
                                    <tr>
                                        <td>{{ book.month|date:"m/Y" }}</td>
                                        <td>{{ book.total_book }}</td>
                                        <td>{{ book.menu_cost|currency }} VNĐ</td>
                                        <td>{{ book.total_cost|currency }} VNĐ</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-12 mt-5">
                    <h2>Doanh thu năm</h2>
                    <div class="card-body table-responsive p-0">
                        <table id="invoice_year_table"
                               class="table table-striped table-valign-middle cell-border table-bordered text-center">
                            <thead>
                                <tr>
                                    <th>Năm</th>
                                    <th>Số phòng thuê</th>
                                    <th>Tiền menu</th>
                                    <th>Doanh thu</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for book in books_year %}
                                    <tr>
                                        <td>{{ book.year|date:"Y" }}</td>
                                        <td>{{ book.total_book }}</td>
                                        <td>{{ book.menu_cost|currency }} VNĐ</td>
                                        <td>{{ book.total_cost|currency }} VNĐ</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- Rooms Section End -->
{% endblock body %}
{% block footer %}
    <style type="text/css">
        .inner>p {
            color: #ffffff;
        }
    </style>
{% endblock footer %}
{% block script %}
    <script type="text/javascript" src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript">
		$("#invoice_month_table").DataTable({
			language: {
                "sSearch": "Tìm kiếm",
                "infoEmpty": "",
				"sInfo": "",
            },
			scrollY: '200px',
            scrollCollapse: true,
            paging: false,
		})
		$("#invoice_year_table").DataTable({
			language: {
                "sSearch": "Tìm kiếm",
                "infoEmpty": "",
				"sInfo": "",
            },
			scrollY: '200px',
            scrollCollapse: true,
            paging: false,
		})
		$("#invoice_day_table").DataTable({
			language: {
                "sSearch": "Tìm kiếm",
                "infoEmpty": "",
				"sInfo": "",
            },
			scrollY: '200px',
            scrollCollapse: true,
            paging: false,
		})

    </script>
{% endblock script %}

hotel_manager/templates/hotels/index.html
{% extends "base.html" %}
{% load static %}
{% load template_support %}
{% load crispy_forms_tags %}
{% block title %}
    Đặt phòng khách sạn
{% endblock title %}
{% block body %}
    <section class="hero-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="hero-text">
                        <h1>Website đặt phòng khách sạn</h1>
                        <p>Chào mừng bạn đến với website của chúng tôi</p>
                        <a href="#" class="primary-btn">Khám phá ngay</a>
                    </div>
                </div>
                <div class="col-xl-4 col-lg-5 offset-xl-2 offset-lg-1">
                    <div class="booking-form">
                        <h3>Đặt phòng khách sạn</h3>
                        <form method="post">
                            {% csrf_token %}
                            {% for field in search_form %}
                                <div class="form-group">
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    <input type="{{ field.field.widget.input_type }}"
                                           name="{{ field.name }}"
                                           class="{{ field.field.widget.attrs.class }}"
                                           value="{{ field.value|check_value_none }}"/>
                                    {% for error in field.errors %}<p style="color: red; position: absolute">{{ error }}</p>{% endfor %}
                                </div>
                            {% endfor %}
                            <button type="submit">Kiểm tra khách sạn</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="hero-slider owl-carousel">
            <div class="hs-item set-bg"
                 data-setbg="{% static 'images/hero/hero-1.jpg' %}"></div>
            <div class="hs-item set-bg"
                 data-setbg="{% static 'images/hero/hero-2.jpg' %}"></div>
            <div class="hs-item set-bg"
                 data-setbg="{% static 'images/hero/hero-3.jpg' %}"></div>
        </div>
    </section>
    <section class="hp-room-section pt-5 pb-5">
        <div class="section-title">
            <h2>Danh sách khách sạn</h2>
        </div>
        <div class="row">
            <div class="col-lg-2"></div>
            <div class="col-lg-8">
                <section class="hp-room-section">
                    <div class="container-fluid">
                        <div class="hp-room-items">
                            <div class="row">
                                {% if hotels %}
                                    {% for  hotel in hotels %}
                                        <div class="col-lg-4 col-md-6 mt-3">
                                            <div class="hp-room-item set-bg"
                                                data-setbg="{{ hotel.hotel_photos.first.image_hotel.url }}">
                                                <div class="hr-text" style="backdrop-filter: blur(10px);">
                                                    <h3>Khách sạn</h3>
                                                    <h2>{{ hotel.name }}</h2>
                                                    <table>
                                                        <tbody>
                                                            <tr>
                                                                <td class="r-o">Email:</td>
                                                                <td>{{ hotel.email }}</td>
                                                            </tr>
                                                            <tr>
                                                                <td class="r-o">Điện thoại:</td>
                                                                <td>{{ hotel.contact_no }}</td>
                                                            </tr>
                                                            <tr>
                                                                <td class="r-o">Địa chỉ:</td>
                                                                <td>{{ hotel.address }}</td>
                                                            </tr>
                                                            <tr>
                                                                <td class="r-o">Thành phố:</td>
                                                                <td>{{ hotel.city }}</td>
                                                            </tr>
                                                            <tr>
                                                                <td class="r-o">Dịch vụ:</td>
                                                                <td>{{ hotel.introduce }}</td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                    <a href="{% url 'hotel_rooms' pk=hotel.pk %}" class="primary-btn">Chi tiết</a>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                {% else %}
                                <div class="col-lg-12 text-center">Không có khách sạn</div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <div class="col-lg-2 row">
            </div>
        </div>
        <div class="row">
            {% if pages.paginator.num_pages > 1 %}
                {% include 'pages.html' %}
            {% endif %}
        </div>
    </section>
{% endblock body %}
{% block footer %}
    <style type="text/css">
        .booking-form form .select-option .nice-select:after {
            border-bottom: 2px solid #dfa274;
            border-right: 2px solid #dfa974;
            height: 10px;
            margin-top: 0;
            right: 20px;
            width: 10px;
            top: 36%;
        }
    </style>
{% endblock footer %}
{% block script %}
    <script type="text/javascript">
        var countries = {{ vietnam_city|safe }}
        $("input[name='city']").autocomplete({
            source: countries
        });
    </script>
{% endblock script %}